import React, { useRef, useState } from 'react';
import { ActivityIndicator, Platform, Pressable, StyleSheet, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import Svg, { Line, Path } from 'react-native-svg';
import { LinearGradient } from 'expo-linear-gradient';
import { Button, Card, Field, Typography as T, tokens } from '@octro/ui';
import { DecimalStringSchema } from '@octro/contracts';
import { demoFixture as fixture, designReference as reference, euro } from './data';
import { useAcknowledge, useClientData, useSession } from './session';
import { useDesktop } from './Shell';
import { Icon } from './Icon';
const c = tokens.color;
function Title({ children }: {
    children: React.ReactNode;
}) { return <T nativeID="screen-title" accessibilityRole="header" {...(Platform.OS === 'web' ? { tabIndex: -1 } : {})} style={s.title}>{children}</T>; }
function Heading({ children }: {
    children: React.ReactNode;
}) { return <T accessibilityRole="header" style={s.heading}>{children}</T>; }
function Note({ children, tone = 'muted' }: {
    children: React.ReactNode;
    tone?: 'muted' | 'warning' | 'success' | 'error';
}) { return <T style={[s.note, { color: c[tone] }]}>{children}</T>; }
function Money({ value, size = 64 }: {
    value: string;
    size?: number;
}) { const { language } = useSession(); return <T style={[s.money, { fontSize: size, lineHeight: size * 1.15 }]}>{euro(value, language)}</T>; }
function Split({ main, aside }: {
    main: React.ReactNode;
    aside?: React.ReactNode;
}) { const desktop = useDesktop(); return <View style={[s.split, desktop && { flexDirection: 'row' }]}><View style={[s.main, desktop && { flex: 1 }]}>{main}</View>{aside && <View style={[s.aside, desktop && { width: 360 }]}>{aside}</View>}</View>; }
function Rail({ children }: {
    children: React.ReactNode;
}) { return <LinearGradient colors={['#382B2E', '#18151B']} style={s.rail}>{children}</LinearGradient>; }
function Notice({ title, children, tone = 'warning' }: {
    title: string;
    children: React.ReactNode;
    tone?: 'warning' | 'success' | 'error';
}) { return <View style={s.notice}><T style={{ color: c[tone] }}>{title}</T><Note>{children}</Note></View>; }
function Row({ title, detail, value, icon = 'circle', positive = false }: {
    title: string;
    detail: string;
    value?: string;
    icon?: string;
    positive?: boolean;
}) { return <View style={s.row}><Icon name={icon}/><View style={{ flex: 1, minWidth: 0, gap: 5 }}><T>{title}</T><Note>{detail}</Note></View>{value && <T style={{ color: positive ? c.success : c.text, fontFamily: tokens.font.medium, textAlign: 'right', maxWidth: '42%' }}>{value}</T>}</View>; }
function EventRows({ short = false }: {
    short?: boolean;
}) {
    const { t, language } = useSession();
    const { data } = useClientData();
    const labels: Record<string, string> = { loyer: t('Loyer', 'Rent'), courses: t('Courses', 'Groceries'), transport: t('Transport', 'Transport'), salaire: t('Salaire', 'Salary') };
    const icons: Record<string, string> = { loyer: 'rent', courses: 'groceries', transport: 'transport', salaire: 'salary' };
    return <View>{data?.events.filter(event => !short || ['loyer', 'salaire'].includes(event.label)).map(event => { const day = event.expected_settlement_at ? Math.round((Date.parse(event.expected_settlement_at) - Date.parse(data.provenance.asOf)) / 86400000) : null; return <Row key={event.id} title={labels[event.label] ?? event.label} detail={`${day === null ? '—' : `J+${day}`} · ${event.direction === 'inflow' ? t('Attendu', 'Expected') : t('Déclaré', 'Declared')}`} value={`${event.direction === 'inflow' ? '+' : '−'}${euro(event.amount.amount_decimal, language)}`} positive={event.direction === 'inflow'} icon={icons[event.label] ?? 'calendar'}/>; })}</View>;
}
function Chart() {
    const { t, language } = useSession();
    return <View style={{ gap: 18 }}>
  <View style={[s.inline, { flexWrap: 'wrap' }]}><View style={s.inline}><View style={{ width: 24, height: 2, backgroundColor: c.text }}/><Note>{t('Sans action', 'Without action')}</Note></View><View style={s.inline}><View style={{ width: 24, borderTopColor: c.success, borderTopWidth: 2, borderStyle: 'dashed' }}/><Note>{t('Avec le plan proposé', 'With the proposed plan')}</Note></View></View>
  <Svg width="100%" height={196} viewBox="0 0 736 196" preserveAspectRatio="none" accessibilityRole="image" accessibilityLabel={t('Illustration synthétique de la prévision. Les valeurs détaillées figurent sous la courbe.', 'Synthetic forecast illustration. Detailed values appear below the chart.')}>
    {[40, 80, 120, 160].map(y => <Line key={y} x1={0} y1={y} x2={736} y2={y} stroke={c.border} strokeWidth={.7}/>)}
    <Line x1={0} y1={162.4} x2={736} y2={162.4} stroke={c.warning} strokeWidth={1}/>
    {reference.chartPaths.map((p, i) => <Path key={i} d={p.geometry} fill="none" stroke={p.stroke === '$success' ? c.success : c.text} strokeWidth={p.strokeWidth}/>)}
  </Svg>
  <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>{['J0', 'J+2', 'J+4', 'J+6', 'J+10'].map(day => <Note key={day}>{day}</Note>)}</View>
  <Note>{t('Repère ambre : réserve à préserver de ', 'Amber line: protected reserve of ')}{euro(fixture.current_reserve, language)}</Note>
  <Note>{t('Illustration fournie · jours relatifs. Sans action : ', 'Provided illustration · relative days. Without action: ')}{reference.pointsWithoutAction.map(v => euro(v, language)).join(' · ')}{t('. Avec le plan : ', '. With the plan: ')}{reference.pointsWithProposal.map(v => euro(v, language)).join(' · ')}.</Note>
  </View>;
}
function TransferSummary() { const { t, language } = useSession(); const { data } = useClientData(); const action = data?.plan.proposed_actions.find(a => a.type === 'own_funds_transfer'); if (!action)
    return <T>{t('Aucune proposition disponible', 'No proposal available')}</T>; return <Rail><Note>{t('ACTION PROPOSÉE', 'PROPOSED ACTION')}</Note><Money value={action.amount_decimal} size={48}/><T style={{ fontSize: 18 }}>{t('Épargne → Compte courant', 'Savings → Current account')}</T><T>{t('Votre courant resterait à ', 'Your current account would remain at ')}{euro(fixture.expected.current_before_salary, language)}{t(' avant le salaire. Votre épargne serait de ', ' before payday. Your savings would be ')}{euro(fixture.expected.savings_remaining, language)}.</T><Notice title={t('Sans nouvelle dette', 'No new debt')} tone="success">{t('Les avoirs restent inchangés au moment du transfert.', 'Total assets remain unchanged at the time of transfer.')}</Notice><Button onPress={() => router.push('/proposal')}>{t('Voir la proposition', 'View proposal')}</Button><Note>{t('Projection, aucun transfert effectué.', 'Forecast, no transfer made.')}</Note></Rail>; }
function Home() {
    const { t, language } = useSession();
    const desktop = useDesktop();
    return <><Title>{t('Bonjour, Lina.', 'Hello, Lina.')}</Title><Split main={<>
  <Card warm style={[s.hero, desktop && { padding: 32 }]}><T>{t('Argent disponible sur le courant', 'Money available in your current account')}</T><Money value={fixture.opening_balances.current} size={desktop ? 72 : 64}/>{desktop ? <T>{t('Épargne : ', 'Savings: ')}{euro(fixture.opening_balances.savings, language)} · {t('Total déclaré : ', 'Declared total: ')}{euro(reference.totalBefore, language)}</T> : <View style={s.between}><T>{t('Épargne', 'Savings')}</T><T>{euro(fixture.opening_balances.savings, language)}</T></View>}<Note>{t('Saisie manuelle · exemple synthétique', 'Manual entry · synthetic example')}</Note></Card>
  {!desktop && <><View style={{ gap: 8, paddingVertical: 4 }}><Heading>{t('Votre loyer arrive avant le salaire', 'Your rent is due before payday')}</Heading><T>{t('À J+6, le courant serait à −130 €. Un transfert de 230 € peut préserver votre réserve.', 'On day 6, the account would reach −€130. A €230 transfer can preserve your reserve.')}</T></View><Button onPress={() => router.push('/calendar')}>{t('Voir mon calendrier', 'View my calendar')}</Button></>}
  {desktop && <Chart />}<View><Heading>{t('Vos prochaines échéances', 'Your upcoming payments')}</Heading><EventRows short/></View>
  {!desktop && <><View style={[s.inline, { paddingVertical: 16 }]}><Icon name="shield"/><T>{euro(fixture.current_reserve, language)}{t(' à préserver sur le courant', ' to preserve in your current account')}</T></View><Button variant="secondary" onPress={() => router.push('/add')}>{t('Ajouter une échéance', 'Add a due date')}</Button></>}
  </>} aside={desktop ? <Rail><Notice title={t('Une attention nécessaire', 'Something needs your attention')}>{t('Le loyer arrive avant le salaire. Le point bas prévu est de −130 €.', 'Rent is due before payday. The forecast low is −€130.')}</Notice><Button onPress={() => router.push('/calendar')}>{t('Voir mon calendrier', 'View my calendar')}</Button><Button variant="secondary" onPress={() => router.push('/add')}>{t('Ajouter une échéance', 'Add a due date')}</Button><Note>{t('Date de référence synthétique : 12 septembre 2026.', 'Synthetic reference date: September 12, 2026.')}</Note></Rail> : undefined}/></>;
}
function Calendar() {
    const { t } = useSession();
    const desktop = useDesktop();
    return <><Title>{t('Calendrier', 'Calendar')}</Title><Split main={<>
  <T style={{ fontSize: desktop ? 20 : 16 }}>{t('Votre courant sur les 30 prochains jours', 'Your current account over the next 30 days')}</T>
  <View style={[s.between, { alignItems: 'flex-end', gap: 16 }]}><View style={{ flex: 1 }}><Money value={reference.pointsWithoutAction[3]!} size={desktop ? 56 : 52}/><Note>{t('Point bas prévu · J+6', 'Forecast low · day 6')}</Note></View><View style={{ maxWidth: '45%', gap: 6 }}><Money value={fixture.expected.current_before_salary} size={30}/><Note>{t('avec le plan proposé', 'with the proposed plan')}</Note></View></View>
  <View style={s.periods}>{[t('7 J', '7 D'), t('14 J', '14 D'), t('30 J', '30 D'), t('3 M', '3 M'), t('1 AN', '1 Y')].map(period => <View key={period} style={[s.period, period === t('30 J', '30 D') && { backgroundColor: c.raised }]}><T style={[s.note, { color: period === t('30 J', '30 D') ? c.text : c.muted }]}>{period}</T></View>)}</View><Note>{t('Horizon fourni : 30 jours. Autres horizons non calculés dans cette démo.', 'Provided horizon: 30 days. Other horizons are not calculated in this demo.')}</Note>
  <Chart />{!desktop && <TransferSummary />}<View><Heading>{t('Vos échéances', 'Your scheduled payments')}</Heading><EventRows /></View>
  </>} aside={desktop ? <TransferSummary /> : undefined}/></>;
}
function Comparison() { const { t, language } = useSession(); const rows = [[t('Compte courant', 'Current account'), fixture.opening_balances.current, reference.pointsWithProposal[0]!], [t('Épargne', 'Savings'), fixture.opening_balances.savings, fixture.expected.savings_remaining], [t('Total des avoirs', 'Total assets'), reference.totalBefore, reference.totalBefore], [t('Avant le salaire', 'Before payday'), reference.pointsWithoutAction[3]!, fixture.expected.current_before_salary]]; return <View><Heading>{t('Avant / avec le plan', 'Before / with the plan')}</Heading>{rows.map(([label, before, after]) => <View key={label} style={[s.row, { flexWrap: 'wrap', justifyContent: 'space-between' }]}><T>{label}</T><View style={s.inline}><T style={{ color: c.muted }}>{euro(before!, language)}</T><Icon name="arrow" size={16}/><T style={{ fontFamily: tokens.font.medium }}>{euro(after!, language)}</T></View></View>)}</View>; }
function Proposal() {
    const { t, language, state } = useSession();
    const { data } = useClientData();
    const ack = useAcknowledge();
    const desktop = useDesktop();
    const action = data?.plan.proposed_actions.find(a => a.type === 'own_funds_transfer');
    if (!action)
        return <T>{t('Aucune proposition disponible', 'No proposal available')}</T>;
    return <>
  <Title>{desktop ? t('Gardez une longueur d’avance.', 'Stay one step ahead.') : t('Une réserve.\nL’esprit tranquille.', 'A reserve.\nPeace of mind.')}</Title><Note>{t('ACTION PROPOSÉE · SANS DETTE', 'PROPOSED ACTION · NO NEW DEBT')}</Note>
  <Split main={<><Card warm style={s.hero}><Money value={action.amount_decimal}/><T>{t('Épargne → Compte courant', 'Savings → Current account')}</T><Note>{t('Aperçu uniquement · aucun virement effectué', 'Preview only · no transfer made')}</Note></Card><Card style={s.detail}><Comparison /><Notice title={t('Réserve de 100 € préservée', '€100 reserve preserved')} tone="success">{t('Le salaire de 1 600 € reste attendu à J+10. Après son arrivée, le courant serait de 1 700 €.', 'The €1,600 salary is still expected on day 10. After it arrives, the current account would reach €1,700.')}</Notice><Note>{t('Ce plan suppose 300 € d’épargne mobilisable, les dépenses prévues et le salaire à la date indiquée.', 'This plan assumes €300 of available savings, the planned expenses and salary on the stated date.')}</Note>{!desktop && <PlanActions />}</Card></>} aside={desktop ? <Rail><Heading>{t('Votre décision', 'Your decision')}</Heading><PlanActions /><Note>{t('Épargne restante : ', 'Remaining savings: ')}{euro(fixture.expected.savings_remaining, language)}</Note></Rail> : undefined}/></>;
}
function PlanActions() { const { t, state } = useSession(); const { data } = useClientData(); const ack = useAcknowledge(); const saved = data?.plan.status === 'ACKNOWLEDGED'; return <View style={{ gap: 16 }}><Button busy={ack.isPending} disabled={!data || state === 'stale'} onPress={() => { if (data)
    ack.mutate(data.plan, { onSuccess: () => router.push('/tracking') }); }}>{saved ? t('Voir le plan enregistré', 'View saved plan') : t('Enregistrer ce plan', 'Save this plan')}</Button>{ack.isError && <T accessibilityRole="alert" style={{ color: c.error }}>{t('Enregistrement impossible. Relisez la proposition.', 'Could not save. Read the proposal again.')}</T>}<Button variant="secondary" onPress={() => router.push('/options')}>{t('Comparer les autres options', 'Compare other options')}</Button><Note>{t('Enregistrer acquitte la proposition dans cette session de démo. Aucun argent n’est déplacé. Le transfert reste à réaliser séparément.', 'Saving acknowledges the proposal in this demo session. No money moves. The transfer must be carried out separately.')}</Note></View>; }
function Sources() { const { t, language } = useSession(); const desktop = useDesktop(); const [info, setInfo] = useState(false); return <><Title>{t('Sources', 'Sources')}</Title><T>{t('Vos données, au même endroit.', 'Your data, in one place.')}</T><Split main={<><Card warm style={s.detail}><Heading>{t('Comptes', 'Accounts')}</Heading><Row title={t('Compte courant', 'Current account')} detail={t('Saisi manuellement · déclaré', 'Entered manually · declared')} value={euro(fixture.opening_balances.current, language)} icon="sources"/><Row title={t('Épargne', 'Savings')} detail={t('Mobilisable dans ce scénario', 'Available in this scenario')} value={euro(fixture.opening_balances.savings, language)} icon="shield"/></Card><Note>{t('Soldes déclarés par vous, non vérifiés par une banque.', 'Balances declared by you, not verified by a bank.')}</Note><View><Heading>{t('Événements & imports', 'Events & imports')}</Heading><Row title={t('4 échéances', '4 scheduled payments')} detail={t('Fixture Lina · saisie déclarative', 'Lina fixture · declared data')} icon="calendar"/><Row title="operations.csv" detail={t('Exemple d’aperçu uniquement · aucun fichier importé', 'Preview example only · no file imported')} icon="file"/></View><Button onPress={() => router.push('/import')}>{t('Importer un fichier', 'Import a file')}</Button><Button variant="secondary" onPress={() => router.push('/add')}>{t('Ajouter une échéance', 'Add a due date')}</Button></>} aside={<Rail><Notice title={t('Connexion facultative', 'Optional connection')}>{t('Vous pouvez continuer avec vos saisies et imports. Aucune connexion bancaire active.', 'You can continue with manual entries and imports. No active bank connection.')}</Notice><Button variant="secondary" onPress={() => setInfo(!info)}>{t('Voir les connexions disponibles', 'View available connections')}</Button>{info && <Note>{t('Aucun connecteur n’est raccordé. La prévision synthétique reste accessible sans wallet ni KYC.', 'No connector is integrated. The synthetic forecast remains available without a wallet or KYC.')}</Note>}<Button variant="ghost" onPress={() => router.push('/calendar')}>{t('Revenir au calendrier', 'Back to calendar')}</Button></Rail>}/></>; }
function Tracking() { const { t } = useSession(); const { data } = useClientData(); const saved = data?.plan.status === 'ACKNOWLEDGED'; const action = data?.plan.proposed_actions.find(a => a.type === 'own_funds_transfer'); if (!action)
    return <T>{t('Aucune proposition disponible', 'No proposal available')}</T>; return <><Title>{t('Suivi', 'Tracking')}</Title><T>{t('Ce qui est prévu. Ce qui a eu lieu.', 'What is planned. What has happened.')}</T><Split main={<><Card warm style={s.hero}><Note>{saved ? t('PROPOSITION ACQUITTÉE', 'PROPOSAL ACKNOWLEDGED') : t('PROPOSITION À LIRE', 'PROPOSAL TO READ')}</Note><Money value={action.amount_decimal}/><T>{t('Épargne → Compte courant', 'Savings → Current account')}</T><Note>{saved ? t('Enregistré dans cette session de démonstration', 'Saved in this demonstration session') : t('Aucune décision enregistrée', 'No decision recorded')}</Note></Card><Notice title={t('Le transfert reste à réaliser', 'The transfer still needs to be made')}>{t('Votre accord enregistre le plan. Il ne modifie pas vos soldes.', 'Your agreement saves the plan. It does not change your balances.')}</Notice><View><Row icon={saved ? 'check' : 'circle'} title={saved ? t('Plan enregistré', 'Plan saved') : t('Plan proposé', 'Plan proposed')} detail={saved ? t('Acquittement simulé · session uniquement', 'Simulated acknowledgement · session only') : t('À lire avant de décider', 'Read before deciding')}/><Row icon="circle" title={t('Transfert à réaliser', 'Transfer to make')} detail={t('Depuis votre banque, séparément', 'Through your bank, separately')}/><Row icon="circle" title={t('Mouvement confirmé', 'Confirmed movement')} detail={t('Aucune observation disponible', 'No observation available')}/></View></>} aside={<Rail><Button onPress={() => router.push('/proposal')}>{saved ? t('Voir le plan enregistré', 'View saved plan') : t('Lire la proposition', 'Read proposal')}</Button><Button variant="secondary" onPress={() => router.push('/sources')}>{t('Mettre à jour mes données', 'Update my data')}</Button><Note>{t('Aucune transaction ni preuve réseau n’a été créée.', 'No transaction or network evidence has been created.')}</Note></Rail>}/></>; }
function Options() { const { t, setState } = useSession(); const { data } = useClientData(); const action = data?.plan.proposed_actions.find(a => a.type === 'own_funds_transfer'); if (!action)
    return <T>{t('Aucune proposition disponible', 'No proposal available')}</T>; return <><Title>{t('Comparer les options', 'Compare options')}</Title><Card warm><Heading>{t('Utiliser vos fonds propres', 'Use your own funds')}</Heading><Money value={action.amount_decimal}/><T>{t('Sans nouvelle dette, avec les hypothèses de Lina.', 'No new debt, under Lina’s assumptions.')}</T><Button onPress={() => router.push('/proposal')}>{t('Voir cette proposition', 'View this proposal')}</Button></Card><Card><Heading>{t('Et si mon épargne était protégée ?', 'What if my savings were protected?')}</Heading><T>{t('Avec 300 € d’épargne protégée, aucune solution sans dette dans ce scénario fourni.', 'With €300 of protected savings, this supplied scenario has no debt-free solution.')}</T><Button variant="secondary" onPress={() => { setState('no-solution'); router.push('/proposal'); }}>{t('Explorer ce scénario', 'Explore this scenario')}</Button></Card><Note>{t('Aucune dépense essentielle n’est reportée sans accord. Aucun crédit n’est activé.', 'No essential expense is deferred without consent. No credit is activated.')}</Note></>; }
function AddEvent() { const { t } = useSession(); const [label, setLabel] = useState(''); const [amount, setAmount] = useState(''); const [date, setDate] = useState(''); const [error, setError] = useState(''); const [saved, setSaved] = useState(false); const input = useRef<TextInput>(null); return <><Title>{t('Ajouter une échéance', 'Add a due date')}</Title><Card style={{ maxWidth: 680 }}><Field ref={input} label={t('Libellé', 'Label')} value={label} onChangeText={setLabel} placeholder={t('Ex. Loyer', 'e.g. Rent')} error={error && !label ? error : undefined}/><Field label={t('Montant en EUR', 'Amount in EUR')} value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="600,00"/><Field label={t('Date prévue (AAAA-MM-JJ)', 'Expected date (YYYY-MM-DD)')} value={date} onChangeText={setDate} placeholder="2026-09-14"/><Note>{t('Cette saisie reste déclarative. Aucun débit n’est confirmé.', 'This entry remains declared. No debit is confirmed.')}</Note>{error && <T accessibilityRole="alert" style={{ color: c.error }}>{error}</T>}<Button onPress={() => { if (!label.trim() || !DecimalStringSchema.safeParse(amount.replace(',', '.')).success || amount.startsWith('-') || !/[1-9]/.test(amount) || !/^\d{4}-\d{2}-\d{2}$/.test(date) || Number.isNaN(Date.parse(date)) || new Date(date).toISOString().slice(0, 10) !== date) {
    setError(t('Vérifiez le libellé, le montant positif et la date.', 'Check the label, positive amount and date.'));
    input.current?.focus();
    return;
} setError(''); setSaved(true); }}>{t('Conserver le brouillon de démo', 'Keep demo draft')}</Button>{saved && <Notice title={t('Brouillon non synchronisé', 'Unsynced draft')} tone="success">{t('Votre saisie reste dans ce formulaire. Elle ne modifie pas la fixture Lina et ne recalcule pas le plan.', 'Your entry remains in this form. It does not change the Lina fixture or recalculate the plan.')}</Notice>}<Button variant="secondary" onPress={() => router.push('/sources')}>{t('Retour aux sources', 'Back to sources')}</Button></Card></>; }
function ImportPreview() { const { t } = useSession(); const [excluded, setExcluded] = useState(false); const [confirmed, setConfirmed] = useState(false); return <><Title>{t('Aperçu de l’import', 'Import preview')}</Title><Note>{t('Exemple synthétique de la maquette · aucun fichier chargé', 'Synthetic design example · no file uploaded')}</Note><Card><Heading>operations.csv</Heading><Row icon="file" title={t('12 lignes détectées dans l’exemple', '12 rows detected in the example')} detail={t('11 lignes distinctes et 1 doublon illustratif', '11 distinct rows and 1 illustrative duplicate')}/><Notice title={t('Un doublon à vérifier', 'One duplicate to check')}>{t('L’exemple contient deux lignes identiques. Excluez le doublon pour continuer.', 'The example contains two identical rows. Exclude the duplicate to continue.')}</Notice><Button variant="secondary" onPress={() => { setExcluded(!excluded); setConfirmed(false); }}>{excluded ? t('Réinclure le doublon', 'Include duplicate again') : t('Exclure le doublon', 'Exclude duplicate')}</Button><Button disabled={!excluded} onPress={() => setConfirmed(true)}>{t('Confirmer l’aperçu de démonstration', 'Confirm demonstration preview')}</Button>{confirmed && <T accessibilityLiveRegion="polite">{t('Aperçu validé : 11 lignes. Aucune importation ni écriture financière effectuée.', 'Preview validated: 11 rows. No import or financial write was performed.')}</T>}<Button variant="ghost" onPress={() => router.push('/sources')}>{t('Retour aux sources', 'Back to sources')}</Button></Card></>; }
function Diagnostic() { const { t, persona, setState } = useSession(); return <><Title>{t('Aucune solution compatible', 'No compatible solution')}</Title><Card><Icon name="shield" color={c.warning} size={32}/><Heading>{persona === 'organization' ? t('Le besoin dépasse la capacité', 'The need exceeds capacity') : t('Votre réserve reste protégée', 'Your reserve remains protected')}</Heading><T>{persona === 'organization' ? t('Besoin : 90 000 €. Plafond : 80 000 €. Résultat de référence : INFEASIBLE.', 'Need: €90,000. Limit: €80,000. Reference result: INFEASIBLE.') : t('Avec 300 € d’épargne protégée, le scénario Lina fourni ne permet pas de solution sans dette.', 'With €300 of protected savings, the supplied Lina scenario has no debt-free solution.')}</T><Note>{t('Diagnostic de démonstration fourni, sans nouvelle action financière. Aucune réserve n’est réduite.', 'Provided demonstration diagnostic, without a new financial action. No reserve is reduced.')}</Note><Button onPress={() => { setState('ready'); router.push('/sources'); }}>{t('Vérifier les données', 'Check data')}</Button></Card></>; }
function Audience() { const { t, persona, setPersona } = useSession(); return <>{persona !== 'organization' && <Title>{persona === 'independent' ? t('Une rentrée prend du retard.', 'An income payment is late.') : t('Votre espace d’organisation', 'Your organization workspace')}</Title>}{persona === 'organization' ? <Diagnostic /> : <Card warm><Note>{t('SCÉNARIO D’ACTIVITÉ SYNTHÉTIQUE', 'SYNTHETIC BUSINESS SCENARIO')}</Note><Heading>{t('Facture attendue, pas encore encaissée', 'Invoice expected, not yet received')}</Heading><T>{t('Les espaces personnel et activité restent séparés. La provision fiscale et les dépenses essentielles sont protégées.', 'Personal and business workspaces remain separate. Tax reserves and essential expenses are protected.')}</T><Notice title={t('Recalcul non raccordé', 'Recalculation not connected')}>{t('Le port applicatif vers le moteur et la fixture contractuelle d’activité sont attendus. Aucun montant de remplacement n’est inventé.', 'The application port to the engine and the business contract fixture are pending. No replacement amounts are invented.')}</Notice></Card>}<Button variant="secondary" onPress={() => { setPersona('personal'); router.push('/demo'); }}>{t('Revenir à Lina', 'Return to Lina')}</Button></>; }
export function Screen({ screen }: {
    screen: string;
}) {
    const { state, setState, persona, t } = useSession();
    const query = useClientData();
    if (state === 'loading' || query.isPending)
        return <><Title>{t('Chargement', 'Loading')}</Title><Card><ActivityIndicator color={c.accent}/><T accessibilityLiveRegion="polite">{t('Chargement des données…', 'Loading data…')}</T>{state === 'loading' && <Button variant="secondary" onPress={() => setState('ready')}>{t('Terminer l’aperçu de chargement', 'Finish loading preview')}</Button>}</Card></>;
    if (state === 'error' || query.isError)
        return <><Title>{t('Données indisponibles', 'Data unavailable')}</Title><Card><T accessibilityRole="alert">{t('Impossible de charger les données. Aucun solde n’a été modifié.', 'Could not load data. No balance has changed.')}</T><Button onPress={() => { setState('ready'); void query.refetch(); }}>{t('Réessayer', 'Try again')}</Button></Card></>;
    if (state === 'empty')
        return <><Title>{t('Commençons simplement.', 'Let’s start simply.')}</Title><Card><T>{t('Aucune donnée dans cet aperçu. Ajoutez une échéance ou découvrez le scénario de Lina, sans wallet ni compte bancaire connecté.', 'No data in this preview. Add a due date or explore Lina’s scenario, without a wallet or connected bank account.')}</T><Button onPress={() => { setState('ready'); router.push('/add'); }}>{t('Ajouter une échéance', 'Add a due date')}</Button><Button variant="secondary" onPress={() => setState('ready')}>{t('Découvrir avec Lina', 'Explore with Lina')}</Button></Card></>;
    if (persona !== 'personal')
        return <Audience />;
    if (state === 'no-solution' && ['proposal', 'calendar', 'home'].includes(screen))
        return <Diagnostic />;
    const pages: Record<string, React.ReactNode> = { home: <Home />, calendar: <Calendar />, sources: <Sources />, proposal: <Proposal />, tracking: <Tracking />, options: <Options />, add: <AddEvent />, import: <ImportPreview /> };
    return <>{state === 'stale' && <Notice title={t('Données anciennes', 'Outdated data')}>{t('Référence synthétique : 12 septembre 2026. Consultation uniquement ; actualisation réelle non raccordée.', 'Synthetic reference: September 12, 2026. Viewing only; live refresh is not connected.')}</Notice>}{state === 'unavailable' && <Notice title={t('Capacité financière indisponible', 'Financial capability unavailable')}>{t('La prévision reste accessible sans wallet, DID, KYC ou crédit.', 'Forecasting remains available without a wallet, DID, KYC or credit.')}</Notice>}{pages[screen] ?? <><Title>{t('Page introuvable', 'Page not found')}</Title><Button onPress={() => router.replace('/demo')}>{t('Retour à l’accueil', 'Back home')}</Button></>}</>;
}
const s = StyleSheet.create({ title: { fontSize: 28, lineHeight: 36, letterSpacing: -.8 }, heading: { fontSize: 20, lineHeight: 28, letterSpacing: -.3 }, note: { fontSize: 13, lineHeight: 20, color: c.muted }, money: { fontFamily: 'Inter_300Light', letterSpacing: -2.5, fontVariant: ['tabular-nums'] }, split: { gap: 32, alignItems: 'stretch' }, main: { gap: 24, minWidth: 0 }, aside: { gap: 24, minWidth: 0 }, rail: { borderRadius: 28, padding: 24, gap: 24 }, hero: { borderRadius: 28, padding: 24, gap: 20, borderWidth: 0 }, detail: { backgroundColor: '#1D191F', padding: 20, gap: 20, borderWidth: 0 }, notice: { backgroundColor: '#2C252A', borderRadius: 16, padding: 16, gap: 8 }, row: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: c.border }, inline: { flexDirection: 'row', alignItems: 'center', gap: 12 }, between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, periods: { flexDirection: 'row', gap: 4 }, period: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 12 } });
